### PR TITLE
typo: arguement -> argument

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@nschonni : Thanks for your contribution! The author, @mamccrea, has been notified to review your proposed change.

**Comment by mamccrea** [comment]
Thanks @nschonni  - we cannot make changes to this repo at this time. I have created a work item to fix the typos when it becomes available again. #please-close

**Comment by nschonni** [comment]
@mamccrea is that specific to these documents? Just asking because some of the others like https://github.com/MicrosoftDocs/azure-reference-other/pull/47 are starting to be merged

**Comment by mamccrea** [comment]
@nschonni - Specifically stream-analytics-query-language

**Comment by mamccrea** [comment]
@nschonni - I wanted to let you know that I made those updates and they are live. Please checkout our Stream Analytics query language content in its new location: https://docs.microsoft.com/en-us/stream-analytics-query/stream-analytics-query-language-reference

**Pull request closed without merging**
