### PR TITLE
Giroux8

### PR DESCRIPTION
**Pull request by dagiro**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@dagiro : Thanks for your contribution! The author, @MikeRys, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@dagiro @MikeRys &nbsp;Hi David and Mike, Would you please submit these changes through the private repo? See PR #23 for details. This PR will be closed. Thanks

**Comment by MikeRys** [comment]
Sorry but David cannot do it through the private repo... and I had no time yet to review and approve. Can we please keep them open and I will get through all of them next week?

**Comment by GitHubber17** [comment]
@dagiro @MikeRys &nbsp;Hi David and Mike, Is this PR ready to be closed? If so, please add the `#please-close` comment. Thanks

**Pull request closed without merging**
