### PR TITLE
Update event-delivery-guarantees-azure-stream-analytics.md

### PR DESCRIPTION
**Pull request by sidramadoss**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@sidramadoss : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mamccrea** [comment]
#sign-off

**Comment by sidramadoss** [comment]
@mamccrea - when can we expect this page to go live? https://docs.microsoft.com/en-us/stream-analytics-query/event-delivery-guarantees-azure-stream-analytics?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fstream-analytics%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json#duplicate-records

**Comment by mamccrea** [comment]
@sidramadoss - this should go live tomorrow.

**Pull request merged**
