### PR TITLE
Update synapsesqlpoolexecrequests.md

### PR DESCRIPTION
**Pull request by jacinda-eng**
Removed ClassifierName as it's not in PROD yet

### CODE REVIEW

**Comment by Jak-MS** [comment]
@rboucher 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rboucher** [comment]
Hi.  This page is autogenerated so any changes will be written over.  It needs to be changed in the backend.

**Comment by rboucher** [comment]
Are you internal to Microsoft @jacinda-eng.  If so email me and I get you to the right place.

**Comment by jacinda-eng** [comment]
Hi Rob,

Yes, I am internal to Microsoft. Email address is ***@***.******@***.***>.

Thanks,
Jacinda

**Comment by rboucher** [comment]
Fixed on the backend.  Closing. 
#please-close

**Pull request closed without merging**
