### PR TITLE
Typo "cognitive services"→"Cognitive Services"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/machine-learning-module-descriptions
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger19** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@JasonWHowell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JasonWHowell** [comment]
#sign-off This is a grammatical fix.

**Comment by PRMerger8** [comment]
@JasonWHowell: I'm sorry - only the author of this article, @xiaoharper, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
