### PR TITLE
Update azurediagnostics.md

### PR DESCRIPTION
**Pull request by josecons-msft**

### CODE REVIEW

**Comment by Court72** [comment]
@EdB-MSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by yossi-y** [comment]
Made some modification and it's approved.

**Comment by yossi-y** [comment]
#sign-off

**Comment by yossi-y** [comment]
Not sure what is the right procedure, I thought I need to give the comment and reviewer, or Ed should commit and merge.
Let me know if I need to do something.

**Comment by EdB-MSFT** [comment]
completed in another PR
#please-close

**Pull request closed without merging**
