### PR TITLE
Resolve syncing conflicts from repo_sync_working_branch to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_working_branch to master.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Taojunshen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@JasonWHowell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@JasonWHowell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@JasonWHowell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@JasonWHowell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JasonWHowell** [comment]
@mamccrea FYI there was a branch merge conflict. We might want to sync master from the public to the private repo. I noticed some date formats were off too, so adjusted that here.

**Pull request merged**
