### PR TITLE
Update extract-n-gram-features-from-text.md

### PR DESCRIPTION
**Pull request by likebupt**
add an example exp for this module

### CODE REVIEW

**Comment by PRMerger18** [comment]
@likebupt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by likebupt** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@likebupt: I'm sorry - only the author of this article, @xiaoharper, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by xiaoharper** [comment]
#sign-off

**Pull request merged**
