### PR TITLE
Update Microsoft.Web/sites metrics table

### PR DESCRIPTION
**Pull request by stashut**
After working with Microsoft.Web/sites I noticed some mismatches with actual metrics and information in documentation

next metrics should be updates: 
**HealthCheckStatus** - actually returns just a timestamp
healthCheckStatus

there are separate metrics **memoryWorkingSet** and **AverageMemoryWorkingSet** but both have Aggregation: Average, there is no sense in AverageMemoryWorkingSet
MemoryWorkingSet

**HttpResponseTime** - actually returns just a timestamp, not matches with what is written in docs
httpResponseTime

**AppConnections** - aggregation: Average only, missed: Count, Maximum, Minimum
AppConnections

**CpuTime** - aggregation: Total only, missed: Count, Minimum, Maximum
CpuTime

In current commit I update only aggregation, if my assumptions will be confirmed - will update next commits

### CODE REVIEW

**Comment by Court72** [comment]
@EdB-MSFT

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by stashut** [comment]
#sign-off

**Comment by EdB-MSFT** [comment]
Hi @stashut 
Thanks for find this.  These articles are generated from json manifest files so changing them here doesn't help.
I'm passing this to the development team to make the appropriate fixes.
Please let us know if you find more issues like this
Thanks
#please-close

**Comment by stashut** [comment]
> Hi @stashut Thanks for find this. These articles are generated from json manifest files so changing them here doesn't help. I'm passing this to the development team to make the appropriate fixes. Please let us know if you find more issues like this Thanks #please-close

Thanks for response @EdB-MSFT 
Is there any way to make PR straight to dev team? 
I identified one more problem

**Pull request closed without merging**
