### PR TITLE
 Update getmetadatapropertyvalue.md

### PR DESCRIPTION
**Pull request by chetanmsft**
Update getmetadatapropertyvalue.md with all property names possible.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@chetanmsft : Thanks for your contribution! The author, @mamccrea, has been notified to review your proposed change.

**Comment by mamccrea** [comment]
#sign-off

**Comment by chetanmsft** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@chetanmsft: I'm sorry - only the author of this article, @mamccrea, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
