### PR TITLE
Update securityevent.md

### PR DESCRIPTION
**Pull request by tduarte14**
Added description for Account, Activity, AzureDeploymentID, Computer, EventData, ManagementGroupName, _ResourceId, SourceSystem, _SubscriptionId, TimeGenerated and Workstation

### CODE REVIEW

**Comment by Court72** [comment]
@bwren

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by tduarte14** [comment]
Hi @bwren , can you please take a look if the changes make sense? That document really need some more detail, hope my few changes help with it. Thanks

**Comment by tduarte14** [comment]
Hi @bwren , can you please take a look if the changes make sense? I understand there must be a lot of requests everyday, but it's been almost 2 weeks since this was done.
Thank you!

**Comment by tduarte14** [comment]
Hi @bwren, can you please take a look if the changes make sense? I understand there must be a lot of requests everyday, but it's been almost 1 month since this was done.
Thank you!

**Comment by tduarte14** [comment]
Hi @bwren, can you please take a look if the changes make sense? I understand there must be a lot of requests every day, but it's been almost 2 months since this was done.
Thank you!

**Comment by bwren** [comment]
@tduarte14 Apologies for the late reply on this. I haven't been monitoring this repo, since these articles are automatically generated from the same source that populates the Log Analytics UI in the Azure portal. Any changes are just going to get overwritten. I know that's not at all clear. We're looking at moving these articles to a private repo to avoid that confusion. In the meantime, I'm looking at adding a note to these articles to at least state that.

I'll see if I can get those descriptions added to the source so they can be generated with the article. It would also populate the UI, so that would help too.

Thanks for the contribution and apologies again for the confusion and for the delay.

**Pull request closed without merging**
