### PR TITLE
Remove "Search services" from resources (AzureActivity table doesn't …

### PR DESCRIPTION
**Pull request by HeidiSteen**
…capture activity for Azure Cognitive Search resources)

### CODE REVIEW

**Comment by PRMerger18** [comment]
@HeidiSteen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by HeidiSteen** [comment]
@ktoliver Can you reopen and process this PR?  First, I don't know what repo this doc is in.  Second, I don't want to fork/clone an entire repo to remove one line.  If we can't fix the doc, then this bug can stay.  No one has complained and it's pretty to easy to figure out that the table isn't viable for a search service.

**Comment by ktoliver** [comment]
@HeidiSteen Sure! You don't need to fork or clone a repo to work in the private repository; you just change the URL to the private repo in the editing pane browser window. We'll leave this PR open, though. Thanks.

**Comment by HeidiSteen** [comment]
#sign-off  Please merge this PR.  I know for a fact that Azure Cognitive Search does not log anything to this table.  It's confusing to see the service listed as a supported resource.  Per OKR "Trust" -- let's fix the inaccuracies in our content.

**Comment by PRMerger9** [comment]
@HeidiSteen: I'm sorry - only the author of this article, @bwren, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
