### PR TITLE
Update docs for hdinsight for windows retirement

### PR DESCRIPTION
**Pull request by heatherbshapiro**
hdinsight on windows retires on july 31. Updating docs with known working scenarios for Linux

### CODE REVIEW

**Comment by PRMerger18** [comment]
@heatherbshapiro : Thanks for your contribution! The author, @rastala, has been notified to review your proposed change.

**Comment by rastala** [comment]
LGTM

**Comment by heatherbshapiro** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@heatherbshapiro: I'm sorry - only the author of this article, @rastala, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by rastala** [comment]
#sign-off

**Pull request merged**
