### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by dagiro**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@dagiro : Thanks for your contribution! The author, @MikeRys, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@dagiro @MikeRys - Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. Read about [article authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.

@dagiro - If you are a Microsoft employee, would you go to https://repos.opensource.microsoft.com/ and join the Microsoft organization? This will update your GitHub profile to show your Microsoft affiliation. 

Thanks

**Comment by MikeRys** [comment]
David is not an employee. I will be reviewing the commits and sign off later this week.

**Comment by GitHubber17** [comment]
@dagiro @MikeRys &nbsp;Hi David and Mike, Would you please submit these changes through the private repo? For significant changes, we need to verify the content by using automation tools that are only available in the private repo. See [this article](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information. This PR will be closed. Thanks

**Pull request closed without merging**
