### PR TITLE
Bulk update: Changing ownership

### PR DESCRIPTION
**Pull request by garyericson**
Changing the author and ms.author values to reassign ownership of all the Machine Learning Studio Reference articles.

### CODE REVIEW

**Comment by garyericson** [comment]
#sign-off 
@rastala @j-martens - Mentioning you in this PR in case there's a question about whether I can change the author values, since I'm not the original author on these.

**Comment by j-martens** [comment]
#sign-off

**Comment by j-martens** [comment]
@garyericson  you in the public repo. Maybe try the private one?

**Comment by rjagiewich** [comment]
@garyericson - Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. [You can use these steps](https://review.docs.microsoft.com/en-us/help/contribute/resolve-merge-conflicts?branch=master#method-2---fetch-the-upstream-references) to pull the commits over to your local copy of the private repo. This pull request is being closed. Thank you.

**Comment by garyericson** [comment]
Shoot! I was working too quickly.

**Pull request closed without merging**
