### PR TITLE
testing what happens when I hand edit this page

### PR DESCRIPTION
**Pull request by rboucher**
Brian, do you get this?

### CODE REVIEW

**Comment by PRMerger9** [comment]
@rboucher : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JasonWHowell** [comment]
@rboucher this is the public repo. Did you want the private repo? https://github.com/MicrosoftDocs/azure-reference-other-pr

**Comment by rboucher** [comment]
Hi @JasonWHowell .  I was testing to see what would happen. The azure-docs-pr closes these automatically if I'm internal.  You don't have to manage the public PRs in this repo, do you?

**Comment by JasonWHowell** [comment]
@rboucher we have an SLA on public PRs, so yes we check them regularly. I have an email report daily from this repo, if you'd like to join let me know.

**Comment by rboucher** [comment]
Okay.  Good to know. Closing.  If we start getting regular updates on our content, @bwren and I will join.

**Pull request closed without merging**
