### PR TITLE
Update awsguardduty-include.md

### PR DESCRIPTION
**Pull request by psriramula**
suggesting sample log file and schema and error code while parsing

### CODE REVIEW

**Comment by psriramula** [comment]
Please review my comments, I am not advising the change, trying to reach the Azure Sentinel team and connector team so that I can get hold of the accepted Json format for including guard duty json

**Comment by American-Dipper** [comment]
@ALIAS - can you review [the comment above](https://github.com/MicrosoftDocs/azure-reference-other/pull/274#issuecomment-1824101478)?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by American-Dipper** [comment]
@EdB-MSFT  - can you review [the comment above](https://github.com/MicrosoftDocs/azure-reference-other/pull/274#issuecomment-1824101478)?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by EdB-MSFT** [comment]
hi @psriramula
Thanks for your dedication to our documentation.
The log reference articles are automatically generated. As such a change made to the markdown file will be overwritten next time the reference is generated. That said, we are working on linking between the supported logs and the log schema references.
For now, please see https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/awsguardduty

**Comment by EdB-MSFT** [comment]
#please-close

**Pull request closed without merging**
