### PR TITLE
replace VS on the note

### PR DESCRIPTION
**Pull request by alexlzx**

### CODE REVIEW

**Comment by alexlzx** [comment]
#sign-off

**Comment by Court72** [comment]
@JasonWHowell 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

Also, can you check that the `author` and `ms.author` listed in the [globalMetadata](https://github.com/MicrosoftDocs/azure-reference-other-pr/blob/main/stream-analytics-docs/docfx.json) are correct and update them in the private repo if needed? Thanks.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alexlzx** [comment]
Thanks for checking. I've already updated the author in the private repo. Please check again.

**Comment by alexlzx** [comment]
#sign-off

**Comment by JasonWHowell** [comment]
@alexlzx Thanks for the fix. Please use the private repo https://github.com/MicrosoftDocs/azure-reference-other-pr/ for future edits to get extra builds/previews/link checks.

**Pull request merged**
